### ISSUE TITLE
Include HTML template in distribution

### ISSUE THREAD

**Issue by sverhoeven** [fair-software/fairtally#26]
Building either #24 or #25 will result in the HTML template from being excluded from the source distribution or wheel distribution.

```
pip install -e .[publishing]
python setup.py sdist bdist_wheel
unzip -l dist/fairtally-0.1.0-py3-none-any.whl |grep index.html
tar -zvtf dist/fairtally-0.1.0.tar.gz |grep index.html
```

**Comment by jspaaks** [comment]
Yes! we should fix that

**Comment by jspaaks** [comment]
Any opinions of MANIFEST v setup.py?

**Comment by sverhoeven** [comment]
No preference, whatever works for including the template in sdist and bdist_wheel.

**Comment by jspaaks** [comment]
Went with MANIFEST.in (PR #25)
