### ISSUE TITLE
Supply URLs in file or on standard input

### ISSUE THREAD

**Issue by sverhoeven** [fair-software/fairtally#27]
I have a list of URLs I would like to check with fairtally. To do this I need concatenate the list with a space char and pass that long string to the cli. It would be nice if I could directly give it my list of URLs as file or on stdin. Where each URL would be on it own line.

For example a file named `urls.txt`
```csv
https://github.com/fair-software/howfairis
https://gitlab.com/jspaaks/howfairis-livetest
```
I would like to be able to call
```
fairtally --urls urls.txt
# or
fairtally < urls.txt
# or
cat urls.txt | fairtally
```

It would be nice option to have next to #3

**Comment by jspaaks** [comment]
I sort of remember that `click` lets you do the `<` option through its `File` argument doesnt it? That should then also take care of the pipe option.

And `--urls` is simple enough to add. Can we think of alternative names for `--urls`?

**Comment by sverhoeven** [comment]
Maybe `--input-file` similar to wget.
