### ISSUE TITLE
Prep release 0.1.0

### ISSUE THREAD

**Issue by fdiblen** [fair-software/fairtally#46]
Add fairtally to
- pypi 
- DockerHub
- Update the Changelog
- Make a GitHub release
- Check Zenodo entry and add the badge

**Comment by sverhoeven** [comment]
In make a release preps

* swap version up and CITATION.cff as version needs to be updated in CITATION.cff
* last step should be to update DOI after Zenodo entry is updated.
* step 3 should link to versioning chapter

**Comment by sverhoeven** [comment]
Release and its preps was made by @eriktks
