### ISSUE TITLE
configure bump2version

### ISSUE THREAD

**Issue by fdiblen** [fair-software/fairtally#54]
We should add bump2version configuration.

**Comment by jspaaks** [comment]
PR was merged, closing

**Comment by sverhoeven** [comment]
Which PR has bumpversion code and configuration? PR #50 only has docs.

**Comment by sverhoeven** [comment]
The bumpversion config should including updating versions in CITATION.cff and .zenodo.json (from #22 )

**Comment by fdiblen** [comment]
fixed in #67
