### ISSUE TITLE
Add sort and filter to rendered report

### ISSUE THREAD

**Issue by jspaaks** [fair-software/fairtally#7]
using JavaScript

**Comment by sverhoeven** [comment]
Sorting support for url, count and badge. Still need sort for recommendations and filters.

**Comment by sverhoeven** [comment]
Can we split sorting and filtering into separate issues? Filtering can be done in many different ways and we should pick one that can answer the users questions.

**Comment by fdiblen** [comment]
We created the following issues: #43 #41
